config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations'
  }
  devise_for :fps, controllers: {
    sessions:       'fps/sessions',
    registrations:  'fps/registrations'
  }
  get 'slots', to: 'slots#index'
  post 'slots/create', to: 'slots#create'
  post 'slots/update', to: 'slots#update'
  get 'slots/render_user_recent', to: 'slots#render_user_recent'
end

app/views/layouts/_alert.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © naraba
  </small>
  <nav>
    <ul>
      <li><%= link_to "このサイトについて", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FP Booking（く）", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li> <%= link_to raw('<span class="glyphicon glyphicon-user"></span>' +
                  "#{current_user.email}"),
                  edit_user_registration_path %></li>
          <li> <%= link_to raw('<span class="glyphicon glyphicon-log-out"></span>
                  ログアウト'),
                  destroy_user_session_path, method: :delete %></li>
        <% elsif fp_signed_in? %>
          <li> <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>' +
                  "#{current_fp.email}"),
                  edit_fp_registration_path %></li>
          <li> <%= link_to raw('<span class="glyphicon glyphicon-log-out"></span>
                  ログアウト'),
                  destroy_fp_session_path, method: :delete %></li>
        <% else %>
          <li> <%= link_to raw('<span class="glyphicon glyphicon-log-in"></span>
                  ログイン'),
                  new_user_session_path %></li>
        <% end %>
        <li><%= link_to image_tag("GitHub-Mark-Light-32px.png",
                        alt: "GitHub Mark",
                        width: 24),
                'https://github.com/naraba/fpbooking' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="robots" content="noindex" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/alert' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>